### ISSUE TITLE
Selecting a new task to compute

### ISSUE THREAD

**Issue by Avierling** [BOINC/boinc-policy#4]
for sure on v7.7.4, prelim check of 7.8.2 seems to indicate also, win 10 x64
Bioc appears to be selecting next task (in the local cache, already downloaded) to run at random. 
Selection should be based on deadline time with oldest being used as next to be computed.

**Comment by ChristianBeer** [comment]
This repository is about the BOINC development policy e.g. the way the BOINC software is developed. This is not a place to discuss how the BOINC software should work. Please look at https://github.com/BOINC/boinc for that.
